<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Akhilesh Pillai" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1: Exploratory Data Analysis</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1: Exploratory Data Analysis</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="data-wrangling-and-data-exploration" class="section level3">
<h3>Data Wrangling and Data Exploration</h3>
<pre class="r"><code>library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(readr)

### Importing data sets
child_mortality_0_5_year_olds_dying_per_1000_born &lt;- read_csv(&quot;child_mortality_0_5_year_olds_dying_per_1000_born.csv&quot;)

income_per_person_gdppercapita_ppp_inflation_adjusted &lt;- read_csv(&quot;income_per_person_gdppercapita_ppp_inflation_adjusted.csv&quot;)

primary_completion_rate_total_percent_of_relevant_age_group &lt;- read_csv(&quot;primary_completion_rate_total_percent_of_relevant_age_group.csv&quot;)</code></pre>
</div>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>The datasets that I picked for this project is child mortality for children ages 0-5 per 1000 births, the income per person (GDP capita inflation adjsuted), and the primary completion rate for the total percent of the relevant age group. These datasets have fairly similar variables. The child mortality dataset has the following variables: year, country, child mortality rate for ages 0-5 (per 1000 births). The income dataset has the following variables: country, year, and income. The primary completion dataset has the following variables: country, year, and % of primary school education completed. I acquired these datasets through a website called gapminder.com, under the data subsection of the site. This data was interesting to me because I wanted to see if income of a country would have any correlation to the child mortality rate and the percent of students who complete their primary school education. These are profound variables that are very commonly studied, and it interested me to identify if these variables relate to each other. I expect that as the income of the country decreases, the child mortality rate should go up and the percent of children who finish their primary school education should should go down. A similarly correlating trend should persist when looking at the increase in the income of a country.</p>
</div>
<div id="tidying-data-sets" class="section level3">
<h3>Tidying Data Sets</h3>
<pre class="r"><code>tidy_childmortality &lt;- child_mortality_0_5_year_olds_dying_per_1000_born %&gt;% 
    pivot_longer(c(&quot;2000&quot;, &quot;2001&quot;, &quot;2002&quot;, &quot;2003&quot;, &quot;2004&quot;, &quot;2005&quot;, 
        &quot;2006&quot;, &quot;2007&quot;, &quot;2008&quot;, &quot;2009&quot;, &quot;2010&quot;, &quot;2011&quot;, &quot;2012&quot;, 
        &quot;2013&quot;, &quot;2014&quot;, &quot;2015&quot;, &quot;2016&quot;, &quot;2017&quot;, &quot;2018&quot;), names_to = &quot;year&quot;, 
        values_to = &quot;cases&quot;)

tidy_primary &lt;- primary_completion_rate_total_percent_of_relevant_age_group %&gt;% 
    pivot_longer(c(&quot;2000&quot;, &quot;2001&quot;, &quot;2002&quot;, &quot;2003&quot;, &quot;2004&quot;, &quot;2005&quot;, 
        &quot;2006&quot;, &quot;2007&quot;, &quot;2008&quot;, &quot;2009&quot;, &quot;2010&quot;, &quot;2011&quot;, &quot;2012&quot;, 
        &quot;2013&quot;, &quot;2014&quot;, &quot;2015&quot;, &quot;2016&quot;, &quot;2017&quot;, &quot;2018&quot;), names_to = &quot;year&quot;, 
        values_to = &quot;primary education&quot;)

tidy_income &lt;- income_per_person_gdppercapita_ppp_inflation_adjusted %&gt;% 
    pivot_longer(c(&quot;2000&quot;, &quot;2001&quot;, &quot;2002&quot;, &quot;2003&quot;, &quot;2004&quot;, &quot;2005&quot;, 
        &quot;2006&quot;, &quot;2007&quot;, &quot;2008&quot;, &quot;2009&quot;, &quot;2010&quot;, &quot;2011&quot;, &quot;2012&quot;, 
        &quot;2013&quot;, &quot;2014&quot;, &quot;2015&quot;, &quot;2016&quot;, &quot;2017&quot;, &quot;2018&quot;), names_to = &quot;year&quot;, 
        values_to = &quot;income&quot;)

tidy_childmortality %&gt;% na.omit()</code></pre>
<pre><code>## # A tibble: 3,705 x 3
##    country     year  cases
##    &lt;chr&gt;       &lt;chr&gt; &lt;dbl&gt;
##  1 Afghanistan 2000  129  
##  2 Afghanistan 2001  125  
##  3 Afghanistan 2002  121  
##  4 Afghanistan 2003  117  
##  5 Afghanistan 2004  113  
##  6 Afghanistan 2005  109  
##  7 Afghanistan 2006  104  
##  8 Afghanistan 2007  100  
##  9 Afghanistan 2008   96  
## 10 Afghanistan 2009   91.9
## # … with 3,695 more rows</code></pre>
<pre class="r"><code>tidy_income %&gt;% na.omit()</code></pre>
<pre><code>## # A tibble: 3,667 x 3
##    country     year  income
##    &lt;chr&gt;       &lt;chr&gt;  &lt;dbl&gt;
##  1 Afghanistan 2000     687
##  2 Afghanistan 2001     646
##  3 Afghanistan 2002    1020
##  4 Afghanistan 2003    1060
##  5 Afghanistan 2004    1030
##  6 Afghanistan 2005    1100
##  7 Afghanistan 2006    1120
##  8 Afghanistan 2007    1250
##  9 Afghanistan 2008    1270
## 10 Afghanistan 2009    1500
## # … with 3,657 more rows</code></pre>
<pre class="r"><code>tidy_primary %&gt;% na.omit()</code></pre>
<pre><code>## # A tibble: 2,304 x 3
##    country     year  `primary education`
##    &lt;chr&gt;       &lt;chr&gt;               &lt;dbl&gt;
##  1 Afghanistan 2016                0.799
##  2 Afghanistan 2017                0.844
##  3 Afghanistan 2018                0.856
##  4 Albania     2000                0.966
##  5 Albania     2001                0.964
##  6 Albania     2003                0.944
##  7 Albania     2004                0.934
##  8 Albania     2007                0.962
##  9 Albania     2008                0.924
## 10 Albania     2009                0.911
## # … with 2,294 more rows</code></pre>
<p>All of the datasets had to undergo a tidy, since they were not so to begin with. In the datasets that I initially had, the column headers were dates. The tidy function was run on these and a new column for each value was created. &quot;tidy_childmortality&quot; created a column for &quot;cases&quot; and a column for &quot;year&quot;. In the &quot;tidy_income&quot; dataset, a new column was made for &quot;year&quot; and &quot;income&quot;. And finally in the &quot;tidy_primary&quot; data set, a new column was made for the &quot;year&quot; and &quot;primary education&quot;. This was done using the pivot_longer function, which created a new column in each of the datasets, one for the year and the other for the respective value. There were some N/A values and those had to be omitted with the na.omit function.</p>
</div>
<div id="joiningmerging-data-sets" class="section level3">
<h3>Joining/Merging Data Sets</h3>
<pre class="r"><code>Merged_Data &lt;- tidy_childmortality %&gt;% left_join(tidy_income) %&gt;% 
    left_join(tidy_primary)</code></pre>
<p>In order to merge the datasets, the left_join function was used. This function was used because it merges all of the data sets based on what columns match in each dataset. To begin with, the tidy_childmortality data set had 3,705 observations with 3 variables. The tidy_income data set had 3,667 observations with 3 variables. The tidy_primary dataset had 3,515 observations with 3 variables. There are two variables in each dataset that were the same, the year and the country.</p>
</div>
<div id="wrangling" class="section level3">
<h3>Wrangling</h3>
<p><strong>Summary Statistics with Core Dplyr Functions</strong></p>
<pre class="r"><code>### Correlation Matrix
cormat &lt;- Merged_Data %&gt;% na.omit() %&gt;% select_if(is.numeric) %&gt;% 
    cor()
cormat</code></pre>
<pre><code>##                        cases     income primary education
## cases              1.0000000 -0.4906608        -0.8344921
## income            -0.4906608  1.0000000         0.3724872
## primary education -0.8344921  0.3724872         1.0000000</code></pre>
<p>The select function was used to create the correlation matrix of all of the numeric values in the merged data. According to this matrix, there is a relatively strong negative correlation between primary education completion rates and child mortality rates. This means that as the the rate of primary education completion goes up, the child mortality rate for children ages 0-5 goes down. When it comes to child mortality rate and income, there is a negative correlation. Even though it is not as strong, this means that as the child mortality rate increases, the income decreases. Finally, there is a weak positive correlation between primary education completion rate and income. As the primary education completion rate goes up, the income also increases, even though it is a weak correlation.</p>
<pre class="r"><code>### Average Income Based on Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize(mean(income, 
    na.rm = T))</code></pre>
<pre><code>## # A tibble: 195 x 2
##    country             `mean(income, na.rm = T)`
##    &lt;chr&gt;                                   &lt;dbl&gt;
##  1 Afghanistan                             1389.
##  2 Albania                                 9050 
##  3 Algeria                                12584.
##  4 Andorra                                41200 
##  5 Angola                                  5686.
##  6 Antigua and Barbuda                    21884.
##  7 Argentina                              17232.
##  8 Armenia                                 6444.
##  9 Australia                              40905.
## 10 Austria                                42884.
## # … with 185 more rows</code></pre>
<p>Using the group_by function, I was able to isolate and calculate the average income for each country. The values are given in the table. Based on this, the country with the highest mean income is Qatar (114,736.8421) and the country with the lowest mean income is Somalia (615.8947).</p>
<pre class="r"><code>### Filter for Year and Sorting by Child Mortality
Merged_Data %&gt;% filter(year == &quot;2018&quot;) %&gt;% arrange(desc(cases, 
    na.rm = T))</code></pre>
<pre><code>## # A tibble: 195 x 5
##    country                  year  cases income `primary education`
##    &lt;chr&gt;                    &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
##  1 Somalia                  2018  122      629              NA    
##  2 Nigeria                  2018  120     5320              NA    
##  3 Chad                     2018  119     1750              NA    
##  4 Central African Republic 2018  116      775              NA    
##  5 Sierra Leone             2018  105     1430               0.818
##  6 Guinea                   2018  101     2340              NA    
##  7 South Sudan              2018   98.6   1770              NA    
##  8 Mali                     2018   97.8   2060              NA    
##  9 Benin                    2018   93     2150              NA    
## 10 Congo, Dem. Rep.         2018   88.1    827              NA    
## # … with 185 more rows</code></pre>
<p>Using the filter and arrange functions, I was able to isolate the data from all the countries into a single year to focus on. I picked 2018, since that was the latest year in all of the datasets. Once I filtered the data to only show data from 2018, I used the arrange function to arrange the data based on cases of child mortality. From this, I can tell that Somalia has the highest child mortality rates, compared to all of the other countries in this dataset.</p>
<pre class="r"><code>### Using mutate function
Merged_Data %&gt;% mutate(cases_by_100 = cases/10)</code></pre>
<pre><code>## # A tibble: 3,705 x 6
##    country     year  cases income `primary education` cases_by_100
##    &lt;chr&gt;       &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;        &lt;dbl&gt;
##  1 Afghanistan 2000  129      687                  NA        12.9 
##  2 Afghanistan 2001  125      646                  NA        12.5 
##  3 Afghanistan 2002  121     1020                  NA        12.1 
##  4 Afghanistan 2003  117     1060                  NA        11.7 
##  5 Afghanistan 2004  113     1030                  NA        11.3 
##  6 Afghanistan 2005  109     1100                  NA        10.9 
##  7 Afghanistan 2006  104     1120                  NA        10.4 
##  8 Afghanistan 2007  100     1250                  NA        10   
##  9 Afghanistan 2008   96     1270                  NA         9.6 
## 10 Afghanistan 2009   91.9   1500                  NA         9.19
## # … with 3,695 more rows</code></pre>
<p>A new variable was created using the mutate function. This new variable, &quot;cases_by_100&quot;&quot;, represents the child mortality rate per every 100 births. The old &quot;cases variable was the child mortality rate per every 1000 births. The mutate function allows us to create a new variable by manipulating another variable in the data set. This is usually helpful to make large numbers smaller on a scale so that analysis is easier.</p>
<p><strong>Summary Statistics With Summary and Group_by</strong></p>
<pre class="r"><code>### Mean of each Variable given the Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize_if(is.numeric, 
    mean, na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country              cases income `primary education`
##   &lt;chr&gt;                &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 Afghanistan          93.4   1389.               0.833
## 2 Albania              15.5   9050                0.959
## 3 Algeria              30.0  12584.               0.970
## 4 Andorra               4.48 41200              NaN    
## 5 Angola              135.    5686.               0.41 
## 6 Antigua and Barbuda  10.5  21884.               1.03</code></pre>
<p>This above shows the mean of each variable and is separated by different countries. This was grouped by country, using the group_by function and then the summarize function was used to calculate the mean of each numeric variable in the dataset.</p>
<pre class="r"><code>### Standard Deviation of each Variable given the Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize_if(is.numeric, 
    sd, na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country             cases income `primary education`
##   &lt;chr&gt;               &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 Afghanistan         21.5    394.              0.0300
## 2 Albania              5.66  2127.              0.0430
## 3 Algeria              5.42  1140.              0.0937
## 4 Andorra              1.13  5904.             NA     
## 5 Angola              43.7   1009.              0.0349
## 6 Antigua and Barbuda  3.01  2113.              0.0682</code></pre>
<p>This above shows the standard deviation of each variable and is separated by different countries. This was grouped by country, using the group_by function and then the summarize function was used to calculate the standard deviation of each numeric variable in the dataset.</p>
<pre class="r"><code>### Variation of each Variable given the Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize_if(is.numeric, 
    var, na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country               cases    income `primary education`
##   &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;               &lt;dbl&gt;
## 1 Afghanistan          462.     155102.            0.000903
## 2 Albania               32.1   4523067.            0.00185 
## 3 Algeria               29.4   1299181.            0.00879 
## 4 Andorra                1.27 34858889.           NA       
## 5 Angola              1910.    1018402.            0.00122 
## 6 Antigua and Barbuda    9.06  4463626.            0.00465</code></pre>
<p>This above shows the variation of each variable and is separated by different countries. This was grouped by country, using the group_by function and then the summarize function was used to calculate the variation of each numeric variable in the dataset. The higher the variation number means that there is more variation within that variable in the data set.</p>
<pre class="r"><code>### Minimum of each Variable given the Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize_if(is.numeric, 
    min, na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country             cases income `primary education`
##   &lt;chr&gt;               &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 Afghanistan         62.3     646               0.799
## 2 Albania              8.82   5440               0.888
## 3 Algeria             23.5   10300               0.802
## 4 Andorra              2.89  31700             Inf    
## 5 Angola              77.2    3890               0.388
## 6 Antigua and Barbuda  6.44  19400               0.926</code></pre>
<p>This above shows the minimum of each variable and is separated by different countries. This was grouped by country, using the group_by function and then the summarize function was used to calculate the minimum of each numeric variable in the dataset.</p>
<pre class="r"><code>### Maximum of each Variable given the Country
Merged_Data %&gt;% group_by(country) %&gt;% summarize_if(is.numeric, 
    max, na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   country              cases income `primary education`
##   &lt;chr&gt;                &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 Afghanistan         129      1810               0.856
## 2 Albania              25.9   12300               1.02 
## 3 Algeria              39.7   13900               1.13 
## 4 Andorra               6.41  51500            -Inf    
## 5 Angola              206      6810               0.462
## 6 Antigua and Barbuda  15.8   26500               1.11</code></pre>
<p>This above shows the maximum of each variable and is separated by different countries. This was grouped by country, using the group_by function and then the summarize function was used to calculate the maximum of each numeric variable in the dataset.</p>
<pre class="r"><code>### Mean of each Variable given the Year
Merged_Data %&gt;% group_by(year) %&gt;% summarize_if(is.numeric, mean, 
    na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   year  cases income `primary education`
##   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 2000   56.3 14236.               0.812
## 2 2001   54.3 14394.               0.836
## 3 2002   52.1 14577.               0.848
## 4 2003   50.1 14900.               0.859
## 5 2004   48.2 15489.               0.862
## 6 2005   46.1 15898.               0.873</code></pre>
<p>This above shows the mean of each variable and is separated by different years. This was grouped by year, using the group_by function and then the summarize function was used to calculate the mean of each numeric variable in the dataset. Since this grouped by year, this data include the numeric values for all of the countries in a given year.</p>
<pre class="r"><code>### Standard Deviation of each Variable given the Year
Merged_Data %&gt;% group_by(year) %&gt;% summarize_if(is.numeric, sd, 
    na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   year  cases income `primary education`
##   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 2000   56.8 18512.               0.252
## 2 2001   55.0 18531.               0.253
## 3 2002   52.9 18653.               0.242
## 4 2003   50.9 18980.               0.222
## 5 2004   48.8 19616.               0.216
## 6 2005   47.0 19624.               0.219</code></pre>
<p>This above shows the standard deviation of each variable and is separated by different years. This was grouped by year, using the group_by function and then the summarize function was used to calculate the standard deviation of each numeric variable in the dataset. Since this grouped by year, this data include the numeric values for all of the countries in a given year.</p>
<pre class="r"><code>### Variation of each Variable given the Year
Merged_Data %&gt;% group_by(year) %&gt;% summarize_if(is.numeric, var, 
    na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   year  cases     income `primary education`
##   &lt;chr&gt; &lt;dbl&gt;      &lt;dbl&gt;               &lt;dbl&gt;
## 1 2000  3231. 342707229.              0.0635
## 2 2001  3020. 343401862.              0.0642
## 3 2002  2798. 347921738.              0.0586
## 4 2003  2589. 360221714.              0.0494
## 5 2004  2384. 384771396.              0.0468
## 6 2005  2207. 385094342.              0.0479</code></pre>
<p>This above shows the variation of each variable and is separated by different years. This was grouped by year, using the group_by function and then the summarize function was used to calculate the variation of each numeric variable in the dataset. Since this grouped by year, this data include the numeric values for all of the countries in a given year.</p>
<pre class="r"><code>### Minimum of each Variable given the Year
Merged_Data %&gt;% group_by(year) %&gt;% summarize_if(is.numeric, min, 
    na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   year  cases income `primary education`
##   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 2000   3.86    573               0.166
## 2 2001   3.6     545               0.194
## 3 2002   3.38    545               0.211
## 4 2003   3.2     558               0.205
## 5 2004   3.06    577               0.238
## 6 2005   2.96    594               0.261</code></pre>
<p>This above shows the minimum value of each variable and is separated by different years. This was grouped by year, using the group_by function and then the summarize function was used to calculate the minimum of each numeric variable in the dataset. Since this grouped by year, this data include the numeric values for all of the countries in a given year.</p>
<pre class="r"><code>### Maximum of each Variable given the Year
Merged_Data %&gt;% group_by(year) %&gt;% summarize_if(is.numeric, max, 
    na.rm = T) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 4
##   year  cases income `primary education`
##   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;               &lt;dbl&gt;
## 1 2000    234 108000                1.19
## 2 2001    229 108000                1.22
## 3 2002    223 111000                1.33
## 4 2003    217 109000                1.2 
## 5 2004    210 117000                1.23
## 6 2005    204 110000                1.35</code></pre>
<p>This above shows the maximum value of each variable and is separated by different years. This was grouped by year, using the group_by function and then the summarize function was used to calculate the maximum of each numeric variable in the dataset. Since this grouped by year, this data include the numeric values for all of the countries in a given year.</p>
</div>
<div id="visualizations" class="section level3">
<h3>Visualizations</h3>
<p><strong>Correlation Heat Map Of Numeric Variables</strong></p>
<pre class="r"><code>col &lt;- colorRampPalette(c(&quot;blue&quot;, &quot;white&quot;, &quot;red&quot;))(20)
heatmap(cormat, col = col, symm = TRUE)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;" /> The graph above shows a heat map for the correlation of the numeric variables in the joined dataset. This graph is basically a visual representation of the correlation matrix. The red boxes mean that there is a positive correlation whereas the blue boxes indicate a negative correlation. The darker the box, the higher the correlation and the lighter the box, the lower the correlation.</p>
<p><strong>Child Mortality vs. % Primary Education Completed with Income Data</strong></p>
<pre class="r"><code>ggplot(Merged_Data, aes(Merged_Data$cases, Merged_Data$`primary education`, 
    color = log10(income)), stat = &quot;summary&quot;) + geom_point(size = 0.5) + 
    scale_y_continuous(&quot;% Primary Education Completion&quot;) + scale_color_gradient(low = &quot;blue&quot;, 
    high = &quot;red&quot;) + labs(color = &quot;Log Income&quot;) + ggtitle(&quot;Child Mortality and % of Primary Education Completed with Income for Countries Around the World&quot;) + 
    scale_x_continuous(&quot;Child Mortality&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-19-1.png" width="672" style="display: block; margin: auto;" /> The ggplot above shows plots child mortality with the % of primary education completion with the log of income as the data points for all of the countries in our dataset. According to this graph, as the child mortality increases the % of primary education completed decreases. This is the expected negative correlation from this data. The income was logged since it helps strengthen the correlation. Countries with higher child mortality rates and lower % of primary education completion rates were found to have lower income, vice versa.</p>
<p><strong>Child Mortality vs. % Primary Education Completed with Income Data</strong></p>
<pre class="r"><code>ggplot(data = Merged_Data, aes(x = Merged_Data$income, y = Merged_Data$cases)) + 
    geom_point(aes(color = Merged_Data$`primary education`)) + 
    stat_smooth(method = &quot;gam&quot;, formula = y ~ s(x), size = 0.5, 
        color = &quot;cyan&quot;) + xlab(&quot;Income&quot;) + scale_y_continuous(name = &quot;Child Mortality&quot;, 
    breaks = c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 
        120, 130, 140, 150, 160, 170, 180, 190, 200)) + ggtitle(&quot;Income vs. Child Mortality with % Primary Education Completion for Countries from 2000-2018&quot;) + 
    labs(color = &quot;% Primary Education Completion&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-20-1.png" width="672" style="display: block; margin: auto;" /> This graph above shows the relationship between income and child mortality with the points being % of primary education completion. There seems to be a negative correlation with income and child mortality. The higher the income, the lower the child mortality rate. When it comes to the % of primary education completed, there is a higher percent in countries that have a higher income level. There is a gradient of decrease in the % of primary education completion as the income decreases. There is also a gradient decrease in the % of primary education completion as the child mortality rate increases which seems to show that as the child mortality rate increases the % of primary education completion decreases. The line seen in this graph follows the points and trends that is seen in the graph.</p>
</div>
<div id="dimensionality-reduction" class="section level3">
<h3>Dimensionality Reduction</h3>
<p><strong>Data Preparation</strong></p>
<pre class="r"><code>### Normalizing The Data
data_norm &lt;- Merged_Data %&gt;% select_if(is.numeric) %&gt;% na.omit %&gt;% 
    scale</code></pre>
<p>The first step of conducted a Principle Component Analysis (PCA) is to prepare the data. The first preparation step is to normalize the data. All of the numeric values were taken, the N/A's were ommitted, and the scale was set to mean=0 and sd=1.</p>
<pre class="r"><code>### Running Princomp
data_pca &lt;- princomp(data_norm)</code></pre>
<pre class="r"><code>### Results Summary
summary(data_pca, loadings = T)</code></pre>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3
## Standard deviation     1.4684677 0.8294832 0.39274688
## Proportion of Variance 0.7191132 0.2294477 0.05143917
## Cumulative Proportion  0.7191132 0.9485608 1.00000000
## 
## Loadings:
##                   Comp.1 Comp.2 Comp.3
## cases              0.639  0.230  0.734
## income            -0.467  0.874  0.133
## primary education -0.611 -0.428  0.666</code></pre>
<p>The summary conducted above provides an overview the princomp that was run on the data. However, in order to determine which variables I want to keep for the PCA analysis, I just have to look at the first part of the summary.</p>
<p><strong>What PC to Keep</strong></p>
<pre class="r"><code>### Calculating Eigenvalues
eigenval &lt;- data_pca$sdev^2

### Variation Explained by Eigenvalues
varprop = round(eigenval/sum(eigenval), 2)

### Plot for Proportion of Variation
ggplot() + geom_bar(aes(y = varprop, x = 1:3), stat = &quot;identity&quot;) + 
    xlab(&quot;&quot;) + geom_path(aes(y = varprop, x = 1:3)) + geom_text(aes(x = 1:3, 
    y = varprop, label = round(varprop, 2)), vjust = 1, col = &quot;white&quot;, 
    size = 5) + scale_y_continuous(breaks = seq(0, 0.6, 0.2), 
    labels = scales::percent) + scale_x_continuous(breaks = 1:3)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Based on the scree plot created above, it seems like all of the variables (PC's) should be kept because the curve does not seem to flatten at any point during the graph.</p>
<pre class="r"><code>### Finding Cumalative Proportion of Variance
round(cumsum(eigenval)/sum(eigenval), 2)</code></pre>
<pre><code>## Comp.1 Comp.2 Comp.3 
##   0.72   0.95   1.00</code></pre>
<p>According to the calculations of cumalative proportion of variance, the PC that I should pick is Comp 1 since those proportions add up to 80%.</p>
<pre class="r"><code>eigenval</code></pre>
<pre><code>##    Comp.1    Comp.2    Comp.3 
## 2.1563974 0.6880424 0.1542501</code></pre>
<p>According to Kaiser's rule, I would pick Comp 1 because the PC value for Comp 1 is the only one that is greater than 1.</p>
<p><strong>Plotting PCA</strong></p>
<pre class="r"><code>### Plotting the PC&#39;s
dataframe &lt;- data.frame(PC1 = data_pca$scores[, 1], PC2 = data_pca$scores[, 
    2])
ggplot(dataframe, aes(PC1, PC2)) + geom_point()</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-27-1.png" width="672" style="display: block; margin: auto;" /> Even though I determined that PC1 was the only adequate PC component to use, I had to use PC2 as well for the graph so that it can be compared to something. According to the graph it is safe to tell that the points along the PC1 axis are not as evenly spread out, which means that they do not influence PC1. When it comes to PC2, the points still do not seem as spread out, but they are more spread out than PC1. This means that even though they have no influence in neither of the PC's, it has slightly more influence on PC2 than it does on PC1.</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
